#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend ghena.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 217986-web-01 18.206.233.133.0:80
        server 217986-web-02 54.227.129.63.0:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
